server:
  port: 8030
 
spring:
  application:
    name: app-zuul

zuul:
  routes:
    demo1:
      path: /test/**
      service-id: app-server
    demo2:
      path: /node/**
      service-id: app-node-service-ip
    demo3:
      path: /config/**
      service-id: app-config-client

eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://docker-eureka-server-container:8000/eureka/
  instance:
    preferIpAddress: true