spring:
  application:
    name: app-config-server
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8040
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://docker-eureka-server-container:8000/eureka/
  instance:
    preferIpAddress: true